# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angela F. Harper
email: harper@fhi.mpg.de
author: Angela F Harper
description: Alexander von Humboldt Fellow, Fritz Haber Institut, Berlin, Germany. PhD in Physics from Cambridge
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: 'Copyright &copy; 2020 Angela Harper. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

#bitbucket_username: harpaf13
#TCM_website: http://www.tcm.phy.cam.ac.uk/profiles/afh41/
#scholar_id: raJAdOUAAAAJ&hl
#linkedin_username: angela.f.harper


# Build settings
markdown: kramdown
permalink : pretty

social:
    - title: twitter
      url: https://twitter.com/physics_ange
    - title: google
      url: https://scholar.google.co.uk/citations?user=raJAdOUAAAAJ&hl=en#
    - title: linkedin
      url: www.linkedin.com/in/angela-f-harper

exclude:
  - Gemfile
  - Gemfile.lock

exclude: [vendor]
