# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angela F. Harper
email: afh41@cam.ac.uk
description: > #This means to ifnore blah
    PhD Candidate in the Theory of Condensed Matter Group, Cavendish Laboratory, University of Cambridge
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: condensedmatter
github_username:  harpaf13
#bitbucket_username: harpaf13
#TCM_website: http://www.tcm.phy.cam.ac.uk/profiles/afh41/
#scholar_id: raJAdOUAAAAJ&hl
#linkedin_username: angela.f.harper


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - about.md
# - news/index.html
# - group/index.html
# - research.md
# - publications/index.md
# - projects.md
# - outreach.md
# - teaching.md

#defaults:
#  -
#    scope:
#      path: "_slides" 
#    values:
#      layout: "iframe"

#collections:
#  slides:
#    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
